# Generated by Django 3.0.7 on 2020-11-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_nama_mahasiswa', models.CharField(max_length=225)),
                ('dataset_judul', models.TextField()),
                ('dataset_deskripsi', models.IntegerField()),
                ('dataset_flie', models.CharField(max_length=225)),
                ('dataset_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='datatest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datates_nama_mahasiswa', models.CharField(max_length=225)),
                ('datates_judul', models.TextField()),
                ('datates_deskripsi', models.IntegerField()),
                ('datates_flie', models.CharField(max_length=225)),
                ('datates_text', models.TextField()),
            ],
        ),
    ]
