# Generated by Django 3.0.7 on 2020-11-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosin_proses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataset_flie',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_text',
            field=models.TextField(null=True),
        ),
    ]
