# Generated by Django 3.0.7 on 2020-11-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosin_proses', '0002_auto_20201119_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataset_deskripsi',
            field=models.TextField(),
        ),
    ]
