# Generated by Django 3.0.7 on 2020-11-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosin_proses', '0003_auto_20201119_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatest',
            name='datates_deskripsi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='datatest',
            name='datates_text',
            field=models.TextField(null=True),
        ),
    ]
