# Generated by Django 3.0.7 on 2020-11-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosin_proses', '0004_auto_20201120_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatest',
            name='datates_flie',
            field=models.FileField(upload_to=''),
        ),
    ]
