# Generated by Django 3.1.4 on 2021-01-01 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kosin_proses', '0005_auto_20201120_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='dataset_deskripsi',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='dataset_nama_mahasiswa',
        ),
    ]
