# Generated by Django 3.1.6 on 2021-03-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kosin_proses', '0007_tf'),
    ]

    operations = [
        migrations.AddField(
            model_name='tf',
            name='dataset_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tf',
            name='dataset_judul',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
